version: '3'

services:
  netboot:
    image: ghcr.io/sio/netboot-server:latest
    environment:
      IPXE_SCRIPT_URL: https://test.url/ipxe.script
    networks:
      - outside
    cap_add:
      - NET_ADMIN

  http:
    image: nginx
    networks:
      - outside

networks:
  outside:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: 192.168.121.0/24
