# Example Docker Compose configuration for the netboot server
#
# URLs, IPs and interface names need to be modified prior to deploying

version: '3'

services:
  netboot:
    image: ghcr.io/sio/netboot-server:latest
    environment:
      IPXE_SCRIPT_URL: ${IPXE_SCRIPT_URL:-http://boot.netboot.xyz}  # HTTPS is not supported by default
      IPXE_SERVER_IP: ${IPXE_SERVER_IP:?required variable}
    networks:
      - outside
    cap_add:
      - NET_ADMIN

networks:
  outside:
    driver: ipvlan
    driver_opts:
      parent: ${IPXE_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: ${IPXE_SERVER_SUBNET:?required variable}
