version: '3'

services:
  netboot:
    image: ghcr.io/sio/netboot-server:latest
    environment:
      IPXE_SCRIPT_URL: http://boot.netboot.xyz  # HTTPS is not supported by default
      IPXE_SERVER_IP: 192.168.121.213
    networks:
      - outside
    cap_add:
      - NET_ADMIN

networks:
  outside:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.121.0/24
