name: docker-build

on:
  push:
    branches:
      - docker
      - master
  schedule:
    - cron: '35 7 15 * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make push
        env:
          DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
