name: docker-build

on:
  push:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '35 7 15 * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make push DOCKER_TAG=${GITHUB_REF##*/}
        env:
          DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
